### ISSUE TITLE
Nolf2 No Music  !

### ISSUE THREAD

**Issue by TP555** [ThreeDeeJay/dsoal#2]
Hi

in No one Lives Forever 2 , no Music will Play  !
Tested DSOAL Version : [[2022-08-17] DSOAL-a90d0cc OpenALSoft-4115df4

**Comment by ThreeDeeJay** [comment]
I just tested the latest official DSOAL builds and music is missing there, too.
So I'll go ahead and close this issue since that's something for kcat to fix in the official/master branch. I wouldn't even know where to start as I'm not really familiar with DSOAL's programming, I just put together the github action to build binaries automatically.
also, it's already been reported here: https://github.com/kcat/dsoal/issues/61#issue-1307534413
